spring:
  application:
    name: loans-reactive
  r2dbc:
    pool:
      enabled: true
      initial-size: 1
      max-size: 20
  sql:
    init:
      mode: never
logging:
  level:
    org.springframework.r2dbc: info